#!/bin/bash



cd Den
bash run.sh
cd ..
cd DVSCF/WFK
bash run.sh
cd ../..
cd GKK/WFK
bash run.sh
cd ../..
cd DVSCF/qpt-0001/WFQ
bash run.sh
cd ../../..
cd DVSCF/qpt-0001/DVSCF
bash run.sh
cd ../../..
cd DVSCF/qpt-0002/WFQ
bash run.sh
cd ../../..
cd DVSCF/qpt-0002/DVSCF
bash run.sh
cd ../../..
cd DVSCF/qpt-0003/WFQ
bash run.sh
cd ../../..
cd DVSCF/qpt-0003/DVSCF
bash run.sh
cd ../../..
cd DVSCF/qpt-0004/WFQ
bash run.sh
cd ../../..
cd DVSCF/qpt-0004/DVSCF
bash run.sh
cd ../../..
cd DVSCF/qpt-0005/WFQ
bash run.sh
cd ../../..
cd DVSCF/qpt-0005/DVSCF
bash run.sh
cd ../../..
cd DVSCF/qpt-0006/WFQ
bash run.sh
cd ../../..
cd DVSCF/qpt-0006/DVSCF
bash run.sh
cd ../../..
cd DVSCF/qpt-0007/WFQ
bash run.sh
cd ../../..
cd DVSCF/qpt-0007/DVSCF
bash run.sh
cd ../../..
cd DVSCF/qpt-0008/WFQ
bash run.sh
cd ../../..
cd DVSCF/qpt-0008/DVSCF
bash run.sh
cd ../../..
cd Mrgddb
bash run.sh
cd ..
cd Mrgdv
bash run.sh
cd ..
cd GKK/qpt-0001/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0001/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0002/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0002/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0003/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0003/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0004/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0004/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0005/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0005/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0006/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0006/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0007/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0007/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0008/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0008/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0009/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0009/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0010/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0010/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0011/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0011/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0012/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0012/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0013/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0013/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0014/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0014/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0015/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0015/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0016/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0016/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0017/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0017/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0018/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0018/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0019/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0019/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0020/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0020/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0021/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0021/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0022/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0022/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0023/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0023/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0024/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0024/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0025/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0025/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0026/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0026/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0027/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0027/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0028/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0028/GKK
bash run.sh
cd ../../..
cd GKK/qpt-0029/WFQ
bash run.sh
cd ../../..
cd GKK/qpt-0029/GKK
bash run.sh
cd ../../..

